### ISSUE TITLE
[Bug] Camera is extremely offset

### ISSUE THREAD

**Issue by fatboychummy** [CreativeMD/CMDCam#101]
# Description
~~After loading a world for the second time~~, all the camera points are weirdly offset. I can also see my player's hitbox just floating there.

Scratch that, it seems that this issue is persisting across worlds. I am unable to use CMDCam at all anymore.

<details><summary>Player hitbox</summary>

![image](https://github.com/user-attachments/assets/8015d265-932a-443d-87dc-8c1e6a6b4879)

</details>

<details><summary>Camera offset and the player hitbox flying around</summary>

https://github.com/user-attachments/assets/7766454d-ea81-4ab8-a656-59889b84bcca

</details>

## Version Details
**Minecraft Version:** 1.20.1
**Forge Version:** 47.3.0
**CMDCam Version:** 2.1.1

## Small extra
I also got this little message instead of a translated message, when pressing the new point key:
![image](https://github.com/user-attachments/assets/15c928d1-64ba-4522-8641-914b4e73a2f7)

**Comment by fatboychummy** [comment]
Logs: https://mclo.gs/DbU9ISs

**Comment by fatboychummy** [comment]
Oh interesting, after doing some extensive testing to narrow down the issue, I think I may have just misunderstood how this mod works. I was simply using `/cam follow` instead of `/cam target`, and I suppose since that would be relative, the camera would be offset, well, relatively.

My mistake.

**Comment by CreativeMD** [comment]
Glad you figured it out. If you need any further help let me know! God bless you!
