### ISSUE TITLE
NullPointerException crash when using outside mode. (CMDCam 1.4.0)

### ISSUE THREAD

**Issue by GrucciNishikino** [CreativeMD/CMDCam#11]
I have been using the beta of CMDCam, and the game crashed with a NullPointerException from CMDCam when I started the camera in outside mode. I created one point, set the mode to outside, and started the animation. This caused the game to crash with [this](https://pastebin.com/6vCpwCaw) report. I have attempted to run the game with the latest Creative Core installed, but this did nothing for me.

**Comment by CreativeMD** [comment]
Fixed it! New version should be available soon. Thanks for reporting this issue!
