### ISSUE TITLE
I don't konw the path of the video

### ISSUE THREAD

**Issue by Acright** [CreativeMD/CMDCam#12]
Minecraft 1.12 ,mod CMDCam. I have selected 3 point and use the command "/cam start 2m" , After  2 minutes,the animation stop. But I can not find the video that I have created using the command. If the mod can not create video. all right.Only to use the Record Screen soft?

**Comment by CreativeMD** [comment]
Unfortunately there is no untegrated recorder, you have to use external software for it.
