### ISSUE TITLE
1.7.10 Issues

### ISSUE THREAD

**Issue by voidswrath** [CreativeMD/CMDCam#13]
Hello...I have been using this mod for quite a bit as camera studio has many issues with other mods and sometimes refuses to load properly. We very much like this mod for 1.7.10 but always have these annoying recurring issues.

Issue 1: Mouse flickers on and off screen

Issue 2: You always go a block or 2 above the point you set if you are inside. Outside is fine.

Hopefully you can help out with making a quick patch. Keep up the good work :)

**Comment by CreativeMD** [comment]
I'm really sorry, but I don't support 1.7.10 anymore. The version for 1.7.10 is a pre-release and not really finished and I never got around to continue it as nobody needed it anyway. I have abandoned 1.7.10 for two years now, it feels bad to disappoint you :( . The project is open source, so anybody can work on it. I can also help out and explain what I did etc. (that's all I can over).
