### ISSUE TITLE
Suggestion: 1.14.3 support

### ISSUE THREAD

**Issue by Patbox** [CreativeMD/CMDCam#16]
Hello. Can you update this mod to 1.14.3. You can use Fabric instead of forge

**Comment by Grid21** [comment]
Can I use forge anyway? It's the only one I will use.

**Comment by CreativeMD** [comment]
No I don't want to switch from Forge, sorry :( . Forge is missing client commands.

**Comment by Patbox** [comment]
Something changed? Can we get mybe a 1.14.4 update? Please...

**Comment by CreativeMD** [comment]
Not possible at the moment, because Forge has not added client commands yet.
