### ISSUE TITLE
Optifine Issue

### ISSUE THREAD

**Issue by Henry-Kidso** [CreativeMD/CMDCam#18]
I really love your mod as I used have to work on 1.7 using camera studio, but as of now I can use 1.12 and its better additions to the game,

but I have come accross and issue with the mod, however I can't determine whether its a CMDCam issue, or a CreativeCore issue; when using any optifine (for 1.12) the outside mode **(/cam mode outside)** breaks, prohibiting me from using both optifine and shaders.

I do really enjoy using this mod, but it would be greatly appreciated if the bug would be looked into, thank you :D

**Comment by CreativeMD** [comment]
That is very weird, never had an issue like it. The outside mode should not be affected by Optifine or shaders. Can you explain what exactly happens? Have you ensured that you are using the newest version of CreativeCore, CMDCam and Optifine. Or there any other mods installed?

**Comment by Henry-Kidso** [comment]
Only decocraft, I will try without

**Comment by Henry-Kidso** [comment]
Yeah with just the 3 mods it still doesnt work.

https://media.giphy.com/media/cj8sEBCuQFKcSI3pzj/giphy.gif

**Comment by CreativeMD** [comment]
Does it work without Optifine though? And the gif doesn't show that much to be honest. It looks like you don't even hit enter. If the console doesn't work for some reason you can also press 'U' to start the camera.

**Comment by Henry-Kidso** [comment]
Sorry I couldn't upload the video anywhere as it's too large, what happens
is when you hit enter everything freezes until the timer runs out, your mod
works fine without optifine, I just thought it'd be nice to have shaders
(not a big deal.)

**Comment by CreativeMD** [comment]
It's quite a big deal. Can you provide me your list of mods?

**Comment by Henry-Kidso** [comment]
[image: image.png]

**Comment by CreativeMD** [comment]
I can't see the image.

**Comment by Henry-Kidso** [comment]
CMDCam_v1.4.4_mc1.12.2
CreativeCore_v1.9.69_mc1.12.2
Optifine_1.12.2_HD_U_F4

**Comment by Henry-Kidso** [comment]
And what happens is you hit play and the screen entirely freezes on the
message that you've just typed "/Cam start [number]" until the timer ends

**Comment by CreativeMD** [comment]
I tested it as well and had absolutely no issues. What forge version are you using (it might be outdated)?

**Comment by Henry-Kidso** [comment]
1.12.2-forge1.12.2-14.23.5.2796

**Comment by CreativeMD** [comment]
Maybe try out a newer version?

**Comment by Henry-Kidso** [comment]
Will do

**Comment by Henry-Kidso** [comment]
Ah, it works when using the latest version rather than the recommended, thank you for your help though.

**Comment by CreativeMD** [comment]
1.12.2 - 14.23.5.2768 is the latest recommended, but good to see it's fixed now! Hope you can enjoy it finally.

**Comment by Henry-Kidso** [comment]
Yeah, I really do enjoy using this mod, I'm glad it's all worked out.
