### ISSUE TITLE
Compatibility  issue with BauerCam (work with the same command)

### ISSUE THREAD

**Issue by Lightone** [CreativeMD/CMDCam#2]
if you have install  the CMDCam  and bauerCam, bauerCam override the command of CMDCam, /cam like this.

tested with the last version Minecraft 1.11.2.

![2017-04-14_14 50 31](https://cloud.githubusercontent.com/assets/2113099/25054472/eedf50d2-2122-11e7-8f5a-89704673de14.png)

**Comment by CreativeMD** [comment]
Ok? Why do you want to have both at the same time?

**Comment by Lightone** [comment]
why not xD
