### ISSUE TITLE
Roll rotation doesn't work

### ISSUE THREAD

**Issue by Tecnok** [CreativeMD/CMDCam#20]
Minecraft version: 1.14.4
CreativeCore installed.
Forge: 28.1.115 
Optifine 1.14.4 HD U F5

Hello, the roll rotation doesn't work when optifine it's installed. The other commands, zoom, etc works. If I delete the optifine, then the rotation works.

I use this mod to create cinematics for a server, so we use shaders and need optifine.

Cheers.

**Comment by CreativeMD** [comment]
This is not an issue of CMDCam but Optifine, I have reported this issue to them. Let's hope they solve it. Can't help you out there sorry :(
