### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Ashergill1** [CreativeMD/CMDCam#22]
Minecraft will not run-up with your mod  CMDCam_V1.4.4 for 1.12.2 and same with v1.4.1

Same with forge 14.23.5.2847, 14.23.5.2803,14.23.5.2768 for 1.12.2
 still happens on my laptop and desktop

If this helps

Desktop:
i7-8700k
64gb
RTX 2070

Laptop:
i7-8750H
16gb
RTX 2060

**Comment by CreativeMD** [comment]
You have to install CreativeCore as well.

**Comment by Ashergill1** [comment]
I have done this and now it is working on my desktop but my laptop still has a problem

**Comment by CreativeMD** [comment]
Can you send me the crash-report?

**Comment by CreativeMD** [comment]
I will close this issue, just open a new issue and provide the crash-report if it still occurs.
