### ISSUE TITLE
Seeing your own Shadow when using Shaders

### ISSUE THREAD

**Issue by FortStomper** [CreativeMD/CMDCam#23]
I'm using the Minecraft1.12 version but I think this problem is on all version: when I start the cam and have a shader on, which gives your Skin a shader when in sunlight, I´m able to see my Shadow. This isn't really a Bug but I hope that you could change it because when your character fly's around, it can look weird. Not sure if the mod works that way, but could you put the player in spectator mode when the camera starts. then the shader wouldn't drop a shadow on the character. The Problem is, my Shader can't disable dropping Shadows, which is why I hope you could change it. Thanks in advance.
Footage of how it looks: https://www.youtube.com/watch?v=cj3wOAhS-MU (time: 3:27-4:00)
Also, I know this isn't A bug and It's not your fault: that's just how shaders work, but If you could change it I would be most grateful

Update: Ok I tested some things and noticed that when I go into game mode 3 (spectator), the cam play will keep me in that game mode. So if i want to hide my shadow I just need to go in gm 3. Maybe you could force the player into gm 3, then they don't have to change it manually.... just an Idea

**Comment by CreativeMD** [comment]
It's not that easy to do, especially on a server. You could also use the outside mode and position the player somewhere outside the camera view.
