### ISSUE TITLE
Timeline between checkpoints

### ISSUE THREAD

**Issue by FortStomper** [CreativeMD/CMDCam#24]
Hey CreativeMD, I had an idea to further enhance your mod. When I have a bunch of checkpoints, which aren't equally far away, no matter which interpolation I use, the speed between the checkpoints will vary between the distance. This can get annoying sometimes when at some point the track gets faster/slower just because the next checkpoint is further/closer away from the former checkpoint. Maybe you could add a tool/command, which sets a time in what time the CMDcam should role regardless of the distance from the checkpoints. Then the speed would stay always the same.

**Comment by CreativeMD** [comment]
I thought about it as well, but then I saw the Blockbuster Mod. If you want to do some advanced stuff you should rather use that one. CMDCam will focus on other stuff. I plan to add a follow camera etc. Not sure when it will be there.
