### ISSUE TITLE
cannot move in outside mode

### ISSUE THREAD

**Issue by ghost** [CreativeMD/CMDCam#27]
title speaks for itself really. i spawn a camera, i set the camera mode to outside, i start it up and i cant move at all. if i enter the camera while moving, my speed will gradually decrease until it hits zero. i need a solution asap.

**Comment by CreativeMD** [comment]
Update, this issue is fixed in the newest version. If it still persists just let me now.

**Comment by ghost** [comment]
i do believe i am using the newest version

**Comment by ghost** [comment]
i am using 1.5.0 in 1.15.2

**Comment by CreativeMD** [comment]
Definitely not the newest version. Use that one: https://www.curseforge.com/minecraft/mc-mods/cmdcam/files/2923575
