### ISSUE TITLE
/cam start time not functioning

### ISSUE THREAD

**Issue by iGamer2003** [CreativeMD/CMDCam#28]
When I type /cam start and time it says invalid time no matter what.  I looked at different videos and all but nothing worked.  Trying to do this for a YT podcast!! Thanks!

**Comment by CreativeMD** [comment]
Make sure to add the time unit. /cam start 10s a number won't be enough. If that doesn't help give me an example which doesn't work for you.

**Comment by iGamer2003** [comment]
IT WORKED! I know I seem silly for asking but thanks so much.

**Comment by CreativeMD** [comment]
Glad to hear it works now!
