### ISSUE TITLE
The "/cam start" command doesn't work

### ISSUE THREAD

**Issue by CJF1215** [CreativeMD/CMDCam#29]
After I create a path and run /cam start [time] it always shows: "No target found", I've tried doing "/cam target none" but it just doesn't work! :(

**Comment by CreativeMD** [comment]
Which version are you using? Would also be helpful if you could send me your log file.

**Comment by CJF1215** [comment]
I'm using 1.15.2 and after doing some testing, it only doesn't work when i set the interpolation do "circular" and the log file; I believe this is the correct file
[latest.log](https://github.com/CreativeMD/CMDCam/files/4535437/latest.log)

**Comment by CreativeMD** [comment]
The circular interpolation requires a target. Just stick to the default interpolation.
https://www.youtube.com/watch?v=mcmqgHNU5Vg
