### ISSUE TITLE
Headless Render Outside mode with (Mo' Bends Mod)

### ISSUE THREAD

**Issue by Lightone** [CreativeMD/CMDCam#3]
hi again xD

tested with recommended forge 1.11.2
CMDCam v1.1.5 mc1.11.2
mobends-0.23.1_for_MC-1.11.2

with that mod the outside mode look like this xD

![2017-05-20_14 43 12](https://cloud.githubusercontent.com/assets/2113099/26278904/11a7eff2-3d6b-11e7-8e9b-22c9bbe32cc8.png)

**Comment by CreativeMD** [comment]
This is a known issue, already reported it to the other, but unfortunately he has not replied yet: https://minecraft.curseforge.com/projects/mo-bends/issues/1338

**Comment by CreativeMD** [comment]
New version of Mo-Bends has finally been released! This issue should not be a thing there anymore.
