### ISSUE TITLE
I can't move

### ISSUE THREAD

**Issue by HeroCrafter1313** [CreativeMD/CMDCam#30]
Hi, I have been looking at many tutorials about the mod and somehow I can't seem to find how to move while the cam is on. I have it on outside mode and I don't know if I am missing anything that is important for you to move. I tried it on my server and also on a singleplayer world and it didn't work. If you can help me, plz respond asap because I really want to use this for my videos

**Comment by CreativeMD** [comment]
Are you using the newest version? There was a bug which prevented it from happening. Or maybe it's caused by Optifine (never tested it in 1.15.2).

**Comment by HeroCrafter1313** [comment]
I downloaded the new version and I can now move. Thank you
