### ISSUE TITLE
Mouse pointer disappears after /cam start

### ISSUE THREAD

**Issue by whitebear60** [CreativeMD/CMDCam#31]
Demo of a bug: [YouTube](https://www.youtube.com/watch?v=GIxnZIyevfI)

**Comment by whitebear60** [comment]
Minecraft v.1.12.2
CMDCam v.1.4.7
CreativeCore v.1.10.13
Forge v.14.23.5.2854

**Comment by CreativeMD** [comment]
Does this version fix your issue?
https://www.dropbox.com/s/rtnmqlidua52wlj/CMDCam_v1.4.8_mc1.12.2.jar?dl=1

**Comment by whitebear60** [comment]
No

**Comment by CreativeMD** [comment]
Released a potential fix, can you try out that version as well?
https://www.curseforge.com/minecraft/mc-mods/cmdcam/files/2967352

**Comment by whitebear60** [comment]
No, mouse pointer disappeared after /cam start.

**Comment by CreativeMD** [comment]
I'm very sorry, but I don't think I can do anything against it. Can you try out if it's fixed in newer versions (minecraft 1.16.3)?

**Comment by CreativeMD** [comment]
I will close this issue for now. If this issue persists in 1.16.3 post it here!

**Comment by whitebear60** [comment]
OK, sure
________________________________
Від: CreativeMD <notifications@github.com>
Надіслано: 28 жовтня 2020 р. 13:47
Кому: CreativeMD/CMDCam <CMDCam@noreply.github.com>
Копія: Mihail Yaremenko <m50421@outlook.com>; Author <author@noreply.github.com>
Тема: Re: [CreativeMD/CMDCam] Mouse pointer disappears after /cam start (#31)


Closed #31<https://github.com/CreativeMD/CMDCam/issues/31>.
