### ISSUE TITLE
I am Invisible in outside mode (with mods, and optifine)

### ISSUE THREAD

**Issue by ButterKing-28** [CreativeMD/CMDCam#32]
when I do /cam mode outside, ect. It does not show me! 
I do have these other mods (other than CMDcam and creative core):
() = related to a mod

- Ambient Sounds

- MrCrayfishes furniture mod

- Gravestones

- Immersive portals

- (Kiwi)

- lost cities

- (mixinBootstrap)

- Music player

- OptiFine

- Snow real magic

- (u team core)

- worldedit

- Xaeros Minimap

With mods:
https://streamable.com/51dcol

Without the other mods:
https://streamable.com/qqrqqj

I am going to add every mod individually until I find the problem...
-Update!-
I have found the issue!!! 
"preview_OptiFine_1.15.2_HD_U_G1_pre18"
Causes this error. I know this because when I add that mod, it shows me as invisible when I get rid of it, I am fine.

**Comment by CreativeMD** [comment]
It's due to Optifine. Can't do anything about it. There are some issue between Optifine and Forge which have to be solved first.

**Comment by ButterKing-28** [comment]
It is fine! 
( ͡° ͜ʖ ͡°)
I am just happy to find the issue. All I have to do is to just move the Optifine mod out of the folder when I am doing an "outside" shot! EZ
Thank you for your help, and I am glad that you tried to help.
( ͡° ͜ʖ ͡°)

**Comment by ButterKing-28** [comment]
I might just close this issue.
