### ISSUE TITLE
/cam start TIME

### ISSUE THREAD

**Issue by Dudrop** [CreativeMD/CMDCam#33]
im useing the 1.15.2 version and I cant seem to get the time function to work, its always just default
I dont know if im not understanding the usage of the command or what but after following several tutorials and trying the command how it says to be uses (/cam start <time|ms|s|m|h|d> [loops (-1 -> endless)] ) nothing works. Please help me figure this out

**Comment by CreativeMD** [comment]
/cam start 10s will play the path for 10 seconds. /cam start start 10m will be 10 minutes etc.

https://www.youtube.com/watch?v=lALYzAdNlXY&list=PLlH1j2SwU8QpCEbKdjYvbQq9vLJXgN426
