### ISSUE TITLE
The given index '0' is too high/low! on clear installation.

### ISSUE THREAD

**Issue by dev-vender** [CreativeMD/CMDCam#34]
I clear installed CMDCam mod and i don't know why but whae i try command like "/cam add 1" or "/cam set 1" i got: The given index '0' is too high/low!

**Comment by CreativeMD** [comment]
Just use `/cam add`, if you add <index> it will try to insert the point before the given index, which is impossible because your list is empty. Same goes for set <index>, it will try to replace the first point, which does not exist.
