### ISSUE TITLE
Player not visible when on outside mode.

### ISSUE THREAD

**Issue by CodyMarkix** [CreativeMD/CMDCam#35]
For some reason, when I use outside mode, my player model doesn't render.
I can still interact with suff, but I can't see myself.

```
Minecraft version: 1.15.2
Forge version: 31.2.30

Mods used:
CMDCam - version 1.5.15
Creative core - version 2.0.5
Optifine HD U G1 pre30

Edit: Resource packs used:
Default Realism
Shield Corrections
```

**Comment by CreativeMD** [comment]
This is an issue of Optifine, use OptiForge, it should fix your issue.
