### ISSUE TITLE
Camera doesn't follow the target

### ISSUE THREAD

**Issue by Fusionlight13** [CreativeMD/CMDCam#4]
When I insert the points and set the camera target it doesn't go around in a smooth motion. Also a lot of times it just faces me the opposite way from where the points are. I have a video of it.
[Archive-9224.zip](https://github.com/CreativeMD/CMDCam/files/1118342/Archive-9224.zip)
 try to use

**Comment by CreativeMD** [comment]
Fixed it in 1.1.8, which should be available soon. Thanks for reporting this issue.
