### ISSUE TITLE
Self target not working [1.12.2]

### ISSUE THREAD

**Issue by opalfirelight** [CreativeMD/CMDCam#41]
I tried  /cam mode outside and then /cam target self but then when I create something it just shows the inside of my skin's head. 
Any help?

**Comment by CreativeMD** [comment]
Is it possible to provide some screenshots or a video?

**Comment by opalfirelight** [comment]
Sorry for not responding so soon, I don't check my email very often. Sure, I'll provide some screenshots!


Start:
![2020-07-26_17 19 10](https://user-images.githubusercontent.com/68475660/88489749-4b95a900-cf64-11ea-90c2-2cdfbcefa63c.png)

Finish:
![2020-07-26_17 19 15](https://user-images.githubusercontent.com/68475660/88489769-75e76680-cf64-11ea-8870-66fe4c4bbba7.png)

**Comment by CreativeMD** [comment]
If you stand too close to the camera it will go inside the head? But I don't see a real bug there. It's hard to see what really happens with these screenshots anyway.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it's still an issue just post some more screenshots or even a video which explains your issue a little bit better.
