### ISSUE TITLE
Command Blocks Dont Have Admin Permission To Start Scenes

### ISSUE THREAD

**Issue by JordanCJbrowne** [CreativeMD/CMDCam#43]
![CMD Cam Command Block Issue](https://user-images.githubusercontent.com/47202371/89739539-7fd29480-da4f-11ea-94d8-db3e53a56b45.PNG)

So the issue is pretty straightforward, I created a small camera path, saved it as "_Betweenlands_Ghoul_", and tried to setup a command block to start the cutscene when a player activates the command block. The problem is, the command block "doesn't have permission", like it needs admin to use the command or something.

The animations work well as a normal command, I'm able to view the path, delete and add points, start the animation, in fact I was absolutely blown away with how easy it was to setup such a powerful camera tool, the only issue is command blocks can't activate the animations for players (like a "cutscene").

Now it might not seem that important, since most players use CMDCam as a all purpose tool to record their maps/gameplay. BUT, overcoming this one obstacle could be GAME CHANGING for Adventure Maps. The mod already saves the camera paths to the world file itself, so, if one were to create adventure maps containing "cutscenes", players could easily download the map and a compatible modpack, and have a GRAND adventure. Command blocks would take care of the work to give the player nice glimpses of new areas they come across.

[Automatic Cutscene Example From Old AdventureCraft](https://youtu.be/nu3HU49U8rk?t=113) {"Cutscene" starts at 2:05)

(You can tell the camera for AdventureCraft back then needed a lot of work, and was a bit speedy in some points, but watching that I'm sure you can understand the level of immersion that adds for someone while they play a map. Luckily CMDCam is more powerful and modern with better depth than what used to be available.)

The link above is an example of basically what it would be like if command blocks could activate a saved animation for any/all players, AdventureCraft is an old, discontinued launcher, but very nostalgic for a small-medium size group of players. 
One of the MAIN things that made it so special was the camera cutscenes that mapmakers could add, CMDCam has much more features and much more potential than that old camera, but somehow you nailed the immersive feeling of what it was like to activate one of those "cutscenes". If you can override this issue for 1.12.2, you would be an absolute miracle worker.

**Comment by CreativeMD** [comment]
I'm absolutely sorry for the issue. It was a very small mistake. Unfortunately I have been very busy, so I couldn't fix it earlier. It should be fixed in the newest version. Thank you very much for your detailed description, really sorry again that it took so long.

**Comment by JordanCJbrowne** [comment]
You are a godsend my friend. It works PERFECTLY. Do not be sorry at all, your timing was perfect.

I'm in the workings of recreating AdventureCraft now since your camera has indulged my inner nostalgia. If you would like to join the Discord specifically for it, feel free https://discord.gg/u8YA9Nt

(The Discord is empty besides me right now because I want to do a big reveal once I have some good maps ready to go and its easy for users to download) but,

I would like to try and maintain two versions of the modpack (One for users with high end PC's and one with just the bare minimal requirements), both ItemPhysics and CMDCam are included in both versions, and LittleTiles is included in the Full version, so if you want to keep up with the Modpack(s) stop on by :D 

But again, thank you so SO SO very much dude, you don't understand how much I appreciate it.

**Comment by CreativeMD** [comment]
Glad I could help! Wish you all the best for you project. If you need any help with my mods just contact me here or via discord.

**Comment by JordanCJbrowne** [comment]
Hey sorry to bother you again so soon, I don't mean to be pushy, I know this isn't really your problem and I mean no disrespect by asking...

But do you know sargunv? Author of "Level Up HP (Forge)". His mod is having the same issue that CMDCam had where the command blocks don't have permission to use commands from the mod.

If you do know him and if it is convenient for you could you please try and help him with a quick fix? Its the last brick wall I have to break down before this modpack is a perfect recreation of AdventureCraft and ready to build maps with.

Again I mean no disrespect and I know you have your own stuff to worry about, but if you think you could pinpoint the fix and help him without feeling like you are wasting your time, it would mean the world to me. 

I only ask because I assume it is as easy as you sending him a message like "Yeah you have to add [code] on line [x] and it'll fix it." And I'm also assuming you may already know each other/be in a chat. Sorry if this comes across as rude. I'm just very excited haha. No hard feelings if there is nothing you can do though, I'm sure he will get around to it.

**Comment by CreativeMD** [comment]
Where can I contact him? It's a very easy fix. He could look at my commit: https://github.com/CreativeMD/CMDCam/commit/bc2f58d826a6af0c7447547c087a6b70adecfd12

**Comment by JordanCJbrowne** [comment]
Thank you for linking that, convenience at it's finest. I sent him the link to your commit on the issue I opened up
https://gitlab.com/sargunv-mc-mods/level-up-hp/-/issues/36 

Since you linked the actual fix, you might not even have to message him, but if you do want to just to clear anything up or give him a pointer, his GitLab is in the link above, I couldn't find an official Discord though.

I cant thank you enough, you've been more than generous about this. I will repay you soon haha.

**Comment by CreativeMD** [comment]
It's very nice to help you out. You are very polite and thankful (unfortunately this doesn't happen too often)! Hope this issue can be solved soon.
