### ISSUE TITLE
I could not record my avatar

### ISSUE THREAD

**Issue by 00Shin00** [CreativeMD/CMDCam#49]
Hi. I hope everything is well with you.

I would just like to ask with how I could record myself considering that I followed the steps, [established points, set the target to me, and had the camera mode outside] but I could not see myself moving. I could see that my avatar could possibly be moving considering after the camera works, I could see my position has changed but I could not capture it on camera.

I was hoping I could record myself whilst using Optifine, Ghoulcraft, and Mizuno 16's craft.

Thank you.

**Comment by 00Shin00** [comment]
For more details, I am currently at 1.16.1. So far, I only tested it out with only tlauncher skin and capes, optifine, creative core, and cmdcam at place.

**Comment by CreativeMD** [comment]
That's an issue of Optifine, there is a new preview version of Optifine for 1.16.3 which fixes it. Otherwise you will have to use OptiForge.

**Comment by 00Shin00** [comment]
Oh, I see. Would I be able to use a 1.16.3 mod on 1.16.1? Thank you.

**Comment by CreativeMD** [comment]
Unfortunately not ...

**Comment by 00Shin00** [comment]
Oh, thank you. Have a wonderful day.
