### ISSUE TITLE
Game crashes on launch 1.12.2 

### ISSUE THREAD

**Issue by crqch** [CreativeMD/CMDCam#53]
Version of Forge: 1.12.2-forge-14.23.5.2855
Version of mod: CMDCam_v1.4.10_mc1.12.2

The Minecraft crashes on launch, even with no other files in .minecraft/mods folder, just the CMDCam. Any ideas?
![image](https://user-images.githubusercontent.com/48185508/117572258-5b851080-b0d2-11eb-86b0-dab9b665b547.png)

**Comment by CreativeMD** [comment]
Install CreativeCore as well.
