### ISSUE TITLE
Cmdcam bug

### ISSUE THREAD

**Issue by Elmonocucuy** [CreativeMD/CMDCam#54]
Hello, I have a strange error in my server.
When I run the cmd-server command it doesn't work. 
It is with magma in 1.12.2 with 70 mods. 
![image](https://user-images.githubusercontent.com/86699970/126727259-0f66520b-0b24-4147-a5f9-66e7b0fb8c18.png)
![image](https://user-images.githubusercontent.com/86699970/126727266-58f2b849-9954-444d-a4c6-45a9b5a6995e.png)
And I use forge 1.12.2 last version

**Comment by CreativeMD** [comment]
Fixed in the newest version. Sorry that it took me so long.
