### ISSUE TITLE
Does not work /cam-server on the server

### ISSUE THREAD

**Issue by Quenteez** [CreativeMD/CMDCam#58]
I use the **CreativeCore** version: **CreativeCore_v2.2.1_mc1.16.5**
I use the **CMDCam** version: **CMDCam_v1.5.22_mc1.16.5** or **CMDCam_v1.5.24_mc1.16.5**.

In a single-player game, everything works fine, as it should, including the /cam-server command. However, on the server, the /cam-server command is defined as unknown (**screenshot:** https://ibb.co/phCZyMB)

**ALSO**: The /cam command itself works, but I don't understand where it saves paths using /cam save [path]. That is, there are no saved paths on the client, nor are there any worlds in the folder on the server (and at the same time, after logging on to the server, these paths can still be loaded using /cam load [path]).

As the core for the server I use **mohist-1.16.5-904- server**.

I would like to use cinematics in order to show them to the players as they progress through the story. But I'm afraid that this is not possible without /cam-server.

Tell me, please, maybe I installed something incorrectly on the server?

**Comment by CreativeMD** [comment]
I'm not sure if it works on an ordinary forge server. Unfortunately I have already dropped support for 1.16. It definitely works for 1.18. So I recommend to update. Sorry for the trouble, but I cannot support every minecraft version + server type. There is no guarantee if you use mohist that forge mods will work.
