### ISSUE TITLE
Don't laugh! But how do you stop a loop?

### ISSUE THREAD

**Issue by gerardvanschip** [CreativeMD/CMDCam#6]
Like the mod, very smooth but when I started a loop with -1 I found myself stuck in that loop. there is no /cam stop or /cam start with no loop or /cam start 1 with one loop. Once an endless loop has started I need to quit my Minecraft client.

Obviously, I must be doing something wrong. Please enlighten me.

**Comment by CreativeMD** [comment]
Oh yes, there is no /cam stop command. I will add this the next days.

As a temporary solution i would suggest to use the start/ stop key which is per default 'u'.

**Comment by CreativeMD** [comment]
v1.2.1 will be available soon and adds /cam stop. Thanks for reporting this issue.
