### ISSUE TITLE
Everything in the first person camera disappear

### ISSUE THREAD

**Issue by Jzorreguiet** [CreativeMD/CMDCam#60]
Hi, I'm having an issue with the first person camera because, when I use cam commands, everything disappears (I mean, I can see but I can't see the hand, "the plus" in the middle and the inventory below). However, it's not because I use 1 command or something like that, but when I use 2 cam commands, which moves me from one place to another (let's say that one command block starts and then, with redstone, the second command block starts somewhere else), everything disappears. Is there any solution? 

Also, I know that it may be kind of obvious, but is there any condition for having this mod in a modpack so then I publish it somewhere?  

If you need a video or something let me know.

**Comment by CreativeMD** [comment]
That's intentional. Most people want to use this camera path to record their screen. Why should a flying camera still show the players hand. It's the same thing as if you would use F1 ingame. Sorry, but their is no way to turn it off.

**Comment by Jzorreguiet** [comment]
I didn't mean that. I mean that it happens AFTER using the camera command. I know that there's no need to show the hand during the camera command being played, but I'm making a Modpack in which there's an "adventure" (I haven't started it though) and I want to make some cinematics. This is what I was talking about: 
https://youtu.be/4l-JId1aT20

**Comment by CreativeMD** [comment]
Can't you press F1 to activate it again? Also which version of minecraft are you using?

**Comment by Jzorreguiet** [comment]
Yeah, I've tried it and it works the F11 method. However, is there any solution without F11 so the player doesn't have to press it? I'm using version 1.17.1

**Comment by CreativeMD** [comment]
Fixed in the newest version for 1.18. I don't support 1.17 anymore, so if you want to have it fixed you need to update.
