### ISSUE TITLE
Hermite interpolation path broken?

### ISSUE THREAD

**Issue by ghost** [CreativeMD/CMDCam#61]
The default interpolation path (hermite - white path) now has a different path than it used to in previous versions of the mod. In previous versions, the path would be a straight line from point 1 to point 2. This makes creating smooth paths, that aren't linear, nearly impossible in the 1.18.2 version of the mod. 

Thanks for any updates, or fixes.
![2022-03-14_17 36 51](https://user-images.githubusercontent.com/85766364/158266009-801b24a9-88b2-4e8b-88e7-e37f23faac4d.png)

**Comment by CreativeMD** [comment]
Should be fixed in the newest CreativeCore version. Thanks for reporting this issue!
