### ISSUE TITLE
Spinning

### ISSUE THREAD

**Issue by FreakShow20** [CreativeMD/CMDCam#63]
I have an issue with the CMDcam mod, when I move or remove a point it breaks the whole thing! like I move one that was in the middle of it and once I got to that point I just spin and I can't get it to stop, and when I came back to my world today everything is gone! like all the work I put in yesterday! I tried doing commands to make it start but it just says "you need at least one point to use this command" I don't know what to do I have tried to look it up but I can't find anything about it!

**Comment by CreativeMD** [comment]
If you want to add or change a point afterwards make sure the rotation is correct. Therefore use the command /cam goto <index> use a point which is close to the one you want to add or edit. CMDCam keeps track of your rotations, which can cause lots of spinning if you add a point later on.

Everything is lost if you leave the world. You need to save the path /cam save <name> and load it again once you join back in /cam load <name>.
