### ISSUE TITLE
1.7.10 Using Cam Mode Outside Causes Camera to Not Work

### ISSUE THREAD

**Issue by TheSimplyChris** [CreativeMD/CMDCam#64]
Issue:

When using /cam mode outside with 2 or more registered points, the camera will not travel as intended. Instead the HUD is disabled and the camera stays first person with my character. I am able to use WASD to move around.

When using /cam mode default, the camera travels as intended.

I would like to be able to see my character as I am able to in other versions. Unfortunately I need to use 1.7.10 at this time for mods.

Versions Used: CMDCam+v1.1.3+mc1.7.10  CreativeCore+v1.3.24+mc1.7.10

**Comment by CreativeMD** [comment]
No idea ... maybe it's caused by another mod. Maybe try it with just CreativeCore and CMDCam installed (that should work in theory). Then readd all the mods and see which mod causes the problem. Unfortunately I can't fix the issue itself, since it's 1.7.10.
