### ISSUE TITLE
CMDCam breaks fov

### ISSUE THREAD

**Issue by Peca21** [CreativeMD/CMDCam#67]
When I open a world with cmdcam installed fov breaks, hand follows fov and sprint fov change is not present.
https://imgur.com/a/CDe0PWe
Forge 1.19 - 41.0.26
CMDCam_FORGE_v2.0.4_mc1.19
CreativeCore_FORGE_v2.6.15_mc1.19

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting it!
