### ISSUE TITLE
Crash Placing Block

### ISSUE THREAD

**Issue by CyanideX** [CreativeMD/CMDCam#68]
In creative, placing a dirt block caused a crash.

https://paste.ee/p/5Waqg

[crash-2022-06-14_22.03.02-client.txt](https://github.com/CreativeMD/CMDCam/files/8905822/crash-2022-06-14_22.03.02-client.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version. You seem to find all the issues :D . Thanks for taking the time to report them.
