### ISSUE TITLE
CMDcam crashes when I tab out during animation.

### ISSUE THREAD

**Issue by NotChomp** [CreativeMD/CMDCam#69]
I was creating a skit, and while doing this i record, play the animation, tab out to put the footage, realize it also tabbed out of the animation, I think its fine, I try to place something, crashes.

It sent this out

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "java.util.function.Consumer.accept(Object)" because "team.creative.cmdcam.client.CamEventHandlerClient.selectingTarget" is null
Exit Code: -1

[crash-2022-06-15_14.03.46-client.txt](https://github.com/CreativeMD/CMDCam/files/8912339/crash-2022-06-15_14.03.46-client.txt)

**Comment by NotChomp** [comment]
Also this is 1.18.2 CMDcam v2.0.0
Creative Core v2.6.10

**Comment by Peca21** [comment]
Found the problem I think
MANIFEST.MF has Implementation-Version: unspecified
Other mods have a version number listed there

**Comment by CreativeMD** [comment]
Ported changes from 1.19 back to 1.18.2. Hope that fixes the issue. I will not support 1.18.2 from here on.
