### ISSUE TITLE
A question from the code~

### ISSUE THREAD

**Issue by PorPit** [CreativeMD/CMDCam#7]
I'm trying to make a mod
but I am very confused

Which position is "Part of set player camera roll" in your code
I just saw a float variable: roll in CMDCam.java
Hope to get your help

**Comment by CreativeMD** [comment]
It's here: https://github.com/CreativeMD/CMDCam/blob/c45bf2d3702e7cfddb9bd621fd91033167569c83/src/main/java/com/creativemd/cmdcam/CamEventHandler.java#L313

Discord might be a better place for this.

**Comment by PorPit** [comment]
thanks!
