### ISSUE TITLE
Crash When Opening Chest in Spectator

### ISSUE THREAD

**Issue by CyanideX** [CreativeMD/CMDCam#70]
https://paste.ee/p/97Nwp

[crash-2022-06-15_20.04.06-client.txt](https://github.com/CreativeMD/CMDCam/files/8915309/crash-2022-06-15_20.04.06-client.txt)

**Comment by CyanideX** [comment]
Actually, I crash when right clicking the air. 😆

**Comment by CreativeMD** [comment]
This time you forgot to update CMDCam.

**Comment by CyanideX** [comment]
Oh, yes. Don't you just love it when you download the file and forget to add it to your instance? 😛
