### ISSUE TITLE
Problem whith cam path folow

### ISSUE THREAD

**Issue by freerig** [CreativeMD/CMDCam#71]
Hello
this is the error report : At least two points are needed!
but I have more than 2 points

**Comment by CreativeMD** [comment]
I need more information, what did you type in and what was the except error returned?

**Comment by freerig** [comment]
it return the exit code -1

**Comment by CreativeMD** [comment]
So it crashes once it starts up? What version are you using?

**Comment by freerig** [comment]
First, I type "/cam target self"
Later, I type "/cam add" 3 times, in 3 different positions
Later, I type "/cam start", which works properly
But when I type "/cam show circualar", that crash,
i am in 1.18.2, on an aternos forge server

**Comment by CreativeMD** [comment]
Ok, so now follow cam ... the circular path has not been tested so far ... not sure if it's the thing you want to use. Furthermore I need the crash-report, that one is located in .minecraft/crash-reports.

**Comment by freerig** [comment]
it is : 
[crash-2022-06-18_12.54.17-client.txt](https://github.com/CreativeMD/CMDCam/files/8933524/crash-2022-06-18_12.54.17-client.txt)

**Comment by freerig** [comment]
and exuse me for my english, i am not very good...

**Comment by freerig** [comment]
what do you mean by "Ok, so now follow cam ... the circular path has not been tested so far ..." ?

**Comment by CreativeMD** [comment]
Fixed this crash in the newest version for 1.19. You should not use the circular mode in it's current state. You can make the path follow an entity.

Use the command `/cam follow self` for example to create a path which is relative to the player. Furthermore enable outside mode using `/cam mode outside`. There will be a white box which represents the follow target, you can now create points relative to this target.

EDIT
I will probably do a video about it soon.

**Comment by YoYomec** [comment]
OK, thank you for your answer and you future video ! 👍

**Comment by freerig** [comment]
OK, thank you for your answer and you future video ! 👍
