### ISSUE TITLE
Command does not work: /cam-server start...       Version Minecraft (1.18.2) Version Mod (2.0.5)

### ISSUE THREAD

**Issue by ivanlokko** [CreativeMD/CMDCam#72]
When I go to write the command `/cam-server start` it doesn't even appear, instead the `/cam-server stop` command does appear.

As this command does not appear, I cannot show the cinematic to the rest of the players, I can only see it with the `/cam start` command.

**Comment by ivanlokko** [comment]
When I go to write the command  `/cam-server start` it doesn't even appear, instead the `/cam-server stop` command does appear.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
