### ISSUE TITLE
Cam path not showing correctly

### ISSUE THREAD

**Issue by ghost** [CreativeMD/CMDCam#73]
Basically, the issue is that when I show any path of the camera, it renders in the skybox and not between the selected points. It's kind of strange so I'll add a picture

The useful info:
- 1.16.5-forge-36.2.33

Mods:
- CMDCam_v1.5.24_mc1.16.5
- CreativeCore_v2.2.1_mc1.16.5

![PathRender](https://user-images.githubusercontent.com/108262327/175894106-689204b6-4e97-49b2-9c97-3a4a1bb8b83b.png)

Btw, thanks for reading this and taking your time to maintain this mod

**Comment by CreativeMD** [comment]
I'm very sorry, but I have stopped the support for 1.16.5. Unfortunately the version for 1.16 has not been used that much, that's why there are a few issues, which will not be fixed :| Hope you can understand that. I highly recommend to move to 1.19. CMDCam 2.0 is out and got a lot of new features.
