### ISSUE TITLE
smoothBeginning conflict with loops

### ISSUE THREAD

**Issue by kfitzgerald** [CreativeMD/CMDCam#74]
When smoothBeginning is enabled, any scene with a non-zero loop value will infinitely loop between the first two points of the scene.

Guessing it has to do with:
https://github.com/CreativeMD/CMDCam/blob/1.19/src/main/java/team/creative/cmdcam/common/scene/run/CamRun.java#L44

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. It is fixed in the newest version, which should be available in a few minutes.
