### ISSUE TITLE
Error while using the command /cam-server

### ISSUE THREAD

**Issue by z0me** [CreativeMD/CMDCam#75]
HI i install the mod in version 1.18.2 and all the commands works correctly i think, but when i type the command /cam-server create...
it gives me an error like this [Server thread/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER also here is my report . https://mclo.gs/zzvw6hf

**Comment by CreativeMD** [comment]
Fixed in the newest version, which should be available in a few minutes. Thanks a lot for reporting this issue!
