### ISSUE TITLE
[1.12.2] Can't control my character during an outside mode camera if I compile the mod myself

### ISSUE THREAD

**Issue by MomoPewpew** [CreativeMD/CMDCam#80]
Hello!

I'm trying to make some minor changes to the mod for a project that I'm doing on a 1.12.2 server. I managed to set up the workspace and compile the mod just fine, but in the version that I compile (without making any changes to the actual code) I can't control my own character while the renderviewentity is set to a different entity.

This even happens in my own sandbox so it's not an incompatibility with a different mod.

Does this sound like a familiar issue that you might be able to advise me on?

**Comment by CreativeMD** [comment]
You forgot this step: https://youtu.be/7Ahshi_QjM4?t=288

**Comment by MomoPewpew** [comment]
Thank you for replying!

I ran through the entire video again and confirmed that everything is set up exactly the same, but sadly I'm still getting the same bug. I also tried running it on the exact same forge version and still got this issue

**Comment by CreativeMD** [comment]
Have you put the files in the mods folder? Because I think your ASM transformer does not start.

**Comment by MomoPewpew** [comment]
Ah I see now. What I got from the video was that the files were supposed to be in "Gradlew Workspace/run/mods" but they're supposed to be in "MDKExample/run/mods".

I put the relevant CoreModLoader in MDKExample/run/mods and now it works.

And when I take the META-INF manifest from the loader and put it into my compiled mod, then the final compiled mod also works.

Thank you so much for taking the time to help me set up this environment!

**Comment by CreativeMD** [comment]
Good to hear it works now! Things are a lot better in 1.19.
