### ISSUE TITLE
/cam-server disappears

### ISSUE THREAD

**Issue by tizu69** [CreativeMD/CMDCam#82]
When reloading with /reload, the /cam-server command disappears. The logs don't reveal anything.

![image](https://user-images.githubusercontent.com/60812901/221641617-f222eca0-65fd-4233-b13f-bb50625ecf4a.png)
This is my modset.

**Comment by tizu69** [comment]
To note: The command appears again after the player quits the world, therefore stopping the internal server.

**Comment by CreativeMD** [comment]
What version of Minecraft are you using?

**Comment by tizu69** [comment]
1.19.2

**Comment by CreativeMD** [comment]
Should be fixed in the newest version for 1.19.4. Sorry I do not support 1.19.2 anymore.
