### ISSUE TITLE
Unknown cam-server commands in 1.18.2

### ISSUE THREAD

**Issue by gpjrh01** [CreativeMD/CMDCam#84]
I have updated the mod to its latest version in minecraft 1.18.2 - I have updated Creative Core as well and I have the following problem:

The /cam command by itself works fine, the problem comes when I try to use the /cam-server command. It just doesn't recognize it and gives me the following message: Unknown command.

My server is Magma and I had no problems in previous versions until I upgraded to 1.18.2.
I don't know if it requires some special permission or it's a bug in the mod.

**Comment by CreativeMD** [comment]
And CMDCam is installed on server side?

**Comment by gpjrh01** [comment]
That's right, it is installed on the server and on the clients.
The strange thing is that in the console does not mark any error, simply the command only sends the message of: Unknown command

**Comment by CreativeMD** [comment]
Can you send me the log file of the server?

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. If the issue persists just post the log file here.
