### ISSUE TITLE
Running if the mod is uninstalled in the server side?

### ISSUE THREAD

**Issue by Zhou-Shilin** [CreativeMD/CMDCam#86]
_Google Translated._
I am the operator of my server, and I want to use CMDCam (as a flat replacement for ReplayMod on the high version Forge side) to shoot a promo for my server. However, when I install CMDCam on the client (and of course its predecessor CreativeCore), and then enter the command "/cam", it says "Unknown command". Why is this? I don't want to install CMDCam on the server side, otherwise my players will have to install the mod to join the server.

Version: CMDCam_FORGE_v2.0.16_mc1.18.2

> Original text:
> 我是我的服务器的腐竹，我想使用CMDCam作为ReplayMod在高版本Forge端的平替，为我的服务器拍摄一个宣传片。但是，当我在客户端安装了CMDCam（当然还有它的前置CreativeCore），然后在输入指令“/cmdcam”，却显示“未知的指令”。这是为什么？我不希望在服务端也安装CMDCam，否则这样我的玩家也必须安装这个mod才能进入服务器了。

**Comment by CreativeMD** [comment]
Sorry forgot to respond. Is it a forge or a vanilla server?

**Comment by Zhou-Shilin** [comment]
> Sorry forgot to respond. Is it a forge or a vanilla server?

Forge, with [CreateMod](https://github.com/Creators-of-Create/Create).

(Sorry, I just clicked the wrong button and close the issue. Now it is reopened.)

**Comment by CreativeMD** [comment]
Does the command work in singleplayer?

**Comment by Zhou-Shilin** [comment]
> Does the command work in singleplayer?

Wait a minute, I'll test for it...

**Comment by Zhou-Shilin** [comment]
Yes, it does.

**Comment by CreativeMD** [comment]
After you have entered the singleplayer and join back on the server, does the command work then?

**Comment by Zhou-Shilin** [comment]
No.

**Comment by CreativeMD** [comment]
Sorry I do not see a way around installed it on server side. This is not an issue in 1.19.4, but seems like it is for 1.18.2.

**Comment by Zhou-Shilin** [comment]
Yes, it's for 1.18.2. Will the mod work if I don't install CMDCam on the server side, but only on the client side? (If I am an operator). If the answer to this question is no, then if I install CMDCam on the server side, must the player also install this mod to join the game?

> [Zhou-Shilin](https://github.com/Zhou-Shilin) commented [3 days ago](https://github.com/CreativeMD/CMDCam/issues/86#issue-1735743014)
> ...
> Version: CMDCam_FORGE_v2.0.16_mc1.18.2

**Comment by CreativeMD** [comment]
Maybe? Just try it out I guess.
