### ISSUE TITLE
[1.19.2] View bobbing gets force-disabled/doesn't work with CMDcam

### ISSUE THREAD

**Issue by VOLKOUL** [CreativeMD/CMDCam#87]
Same thing with Minema Resurrection 2.

**Comment by CreativeMD** [comment]
Can you please elobrate further what you mean with that statement? Sorry I should have responded a lot earlier, but better late than never.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists post more information here and I will reopen it.
