### ISSUE TITLE
Can't Zoom

### ISSUE THREAD

**Issue by HybridHenderson** [CreativeMD/CMDCam#88]
CMDcam seems to disable zoom for both minecraft's Spyglass and mods that zoom. Removing it is my only solution.
![image](https://github.com/CreativeMD/CMDCam/assets/137430807/6dfa11de-52e6-4771-8f46-0f9c26a0c6d3) 
![image](https://github.com/CreativeMD/CMDCam/assets/137430807/947e4f42-ed4d-4c33-a245-c76e88e302c4)

**Comment by CreativeMD** [comment]
What version of Minecraft are you using?

**Comment by HybridHenderson** [comment]
1.19.2

**Comment by CreativeMD** [comment]
This issue has been fixed in the newer version. Unfortunately I do not support 1.19 anymore. I highly recommend to switch to 1.20.1 if possible. Sorry for the trouble, but I just do not have the time and motivation to support all these different minecraft versions.

**Comment by HybridHenderson** [comment]
aw man, I cant really move cause alot of mods I got are 1.19.2

oh well, thanks anyways
