### ISSUE TITLE
Camera point glitch.

### ISSUE THREAD

**Issue by robotsimmer** [CreativeMD/CMDCam#9]
Whenever i set P1 and P2 the camera pov moves up. What do i do to fix that?

**Comment by CreativeMD** [comment]
Can you send me a few screenshots or a video?

**Comment by robotsimmer** [comment]
So the first two screenshots are where i set the points.
The third screenshot is when i start the camera and the pov it gives me.

P1 - https://imgur.com/dusXt2p
P2 - https://imgur.com/if3vKn1
P3 = (When i start the camera) https://imgur.com/IA71hhV

**Comment by CreativeMD** [comment]
Maybe you were in third person?

**Comment by robotsimmer** [comment]
No. I was using first person. The mod worked fine when i started using it a few days ago and now it's acting weird.

**Comment by robotsimmer** [comment]
It only happens with the 1.7.10 version 11.2 works fine.

**Comment by CreativeMD** [comment]
Sorry, but I don't support 1.7.10 anymore :( If you are stuck to that version I recommend to use Camera Studio instead: http://www.sushenlab.com/
