### ISSUE TITLE
Rolling not working while cgm is installed

### ISSUE THREAD

**Issue by VulpesStella** [CreativeMD/CMDCam#90]
For details see [MikhailTapio/MrCrayfishGunMod#5](https://github.com/MikhailTapio/MrCrayfishGunMod/issues/5), this also happens with the official cgm(1.19.2-1.3.7).

**Comment by CreativeMD** [comment]
Responded over there.

**Comment by VulpesStella** [comment]
Thx a lot!

**Comment by CreativeMD** [comment]
Oh thanks a lot! Great job!
