### ISSUE TITLE
Making transitions why teleporting the player to a point

### ISSUE THREAD

**Issue by LOUDO56** [CreativeMD/CMDCam#92]
Hello, this is more a question rather than an issue.
While testing this mod, I could not find anything that can create transitions by teleporting to a point.
For example: I have 4 points. I want the player to move from point 1 to point 2 then it teleports to point 3 and move to point 4.

I tried to find an solution but i could not find anything, so I am opening this issue to know if it possibles or not?

Best regards.

**Comment by CreativeMD** [comment]
Hey, sorry for not responding earlier. This is not possible. However you can create two paths and save them to the server and run them via command blocks. Then you can start the second path using a timer which will have the same effect as the teleport.

**Comment by LOUDO56** [comment]
Alright. Thank you for your answer!
