### ISSUE TITLE
[Bug Report] Running `/reload` Breaks `/cam-server` Completely

### ISSUE THREAD

**Issue by V0calgiant12** [CreativeMD/CMDCam#93]
**_When you boot up a world, `/cam-server` works completely fine. However, if you were to run `/reload`, you will find that to no longer be the case._**
Version: _1.19.2, may affect others._
Forge Version: _Any_

**How to reproduce:**
Step 1: Load up any world file.
Step 2: Type in `/cam-server` to verify it works.
![2024-04-26_20 24 33](https://github.com/CreativeMD/CMDCam/assets/109500471/57336e41-2f20-4290-81e0-d69a880dec3e)
Step 3: Run `/reload`
![2024-04-26_20 24 42](https://github.com/CreativeMD/CMDCam/assets/109500471/4b10a991-fdae-4d5d-b3e3-6f5c5375aeb6)
Step 4: Attempt to run `/cam-server` again. It will no longer work.
![2024-04-26_20 25 01](https://github.com/CreativeMD/CMDCam/assets/109500471/34e26676-31b7-479d-a247-4f18b9f80af5)

Note: This was done on a completely new client with nothing except CMDCam and CreativeCore installed on the latest version of Forge for 1.19.2,

**Comment by CreativeMD** [comment]
Sorry but I do not support 1.19.2 anymore. I'm pretty sure this issue got fixed in newer version. If you can update to 1.20.1, otherwise you will have to live with it.
