### ISSUE TITLE
The cam-server add command doesn't work 

### ISSUE THREAD

**Issue by NoMoreUsernames999** [CreativeMD/CMDCam#95]
In CmdCAM v1.4.12, this command always fails to run with the error message <invalid number "path">
It seems creating paths this way is only supported if the name is an integer and not a string.
Edit: Also want to add that this command 90% of the time just breaks completely. If you use "\~" to set the coord points, the entire render engine just shits itself and all blocks disappear until a block in the chunk updates, and then that chunk alone starts to render. If using "\~" with numeral increments (i.e 5 or -6) then the same thing happens, but the cam starts to jitter all over the place or zoom across the world.

**Comment by CreativeMD** [comment]
Sorry, but this old version is not supported anymore. I highly recommend to update if possible.
