### ISSUE TITLE
FOV bug

### ISSUE THREAD

**Issue by TysonTheEmber** [CreativeMD/CMDCam#98]
When flying, the fov pulses in and out. I think this has something to do with the zoom function. , I have not tested it with only CMDCam but I think the issue will persist as it doesn't seem to conflict with other mods. https://cdn.discordapp.com/attachments/1252455027537350666/1252456266710913024/Project_Ember-_EmberCraft-CMDCam_bug.zip?ex=667399cb&is=6672484b&hm=293c4a61dd9aeb3ae122d6dce53f34f1be0e20740d6291cc63f055e208c0b415&

**Comment by TysonTheEmber** [comment]
Found issue, FPS Reducer setting on riding/flying causing fov changes and rubberbanding. Simply disable this setting and you should be good.

**Comment by CreativeMD** [comment]
If you remove CMDCam does the issue persist? Sorry for responding late. Unfortunately the content of the link is not available anymore.

**Comment by CreativeMD** [comment]
Will close this due to inactivity.

**Comment by TysonTheEmber** [comment]
Sorry For the late reply, I reached out on discord and was told 1.18.2 is no longer supported. Its likely a issue with lag(idk if its mspt or fps tied) but when the client lags it tries to reset or change the CMDCam fov/zoom and because its separate from MC fov it conflicts. I said flying because I was loading chunks, thus lag. I don't know if this bug is persistent in later versions but it should be easy to test by, for example, using a command block to spawn a bunch of things.

**Comment by CreativeMD** [comment]
There is actually not a good way to fix this issue. In past case the fps should not drop heavily once chunks are loaded, but CMDCam does not have a system to keep chunks loaded.
